#!/bin/csh
# Run linking
set scenario=$1
set segment=$2
set seg = $segment
set tempdir=$3
set tree = $MODEL_ROOT
source $MODEL_ROOT/config/control/script/${scenario}.con
cd $tempdir

set cols = ( OVOL )
set dsns = ( 111 )
set num = ${#cols[@]}
while ( i <= num )
  set col = $cols[$i]
  set dsn = $dsns[$i]
  # Prep outflow data for export to river wdm
  set wdmcsv = ${seg}_${col}'.csv'
  echo "Notice: Rscript $MODEL_ROOT/run/export/csv_export_wdm_format.R $csvfile $wdmcsv $col"
  Rscript $MODEL_ROOT/run/export/csv_export_wdm_format.R $csvfile $wdmcsv ROVOL
  # Push ROVOL into wdm
  # copy here cause it is hardto send these paths to wdm_insert_one, need escape?
  cp /usr/local/lib/hspf/message.wdm ./
  echo ${seg}.wdm $wdmcsv $dsn 1 w message.wdm | wdm_insert_one
end
