#!/bin/csh
# Run post-process extract routine
set scenario=$1
set segment=$2
set tempdir=$3
set tree = $MODEL_ROOT
source $MODEL_ROOT/config/control/script/${scenario}.con

# move all files to the model data archive
set mod="hydr"
set h5file = $seg'.h5'
mv *.csv $CBP_EXPORT_DIR/river/$scenario/$mod/ -f
chgrp $MODEL_FILES_GROUP $CBP_EXPORT_DIR/river/$scenario/$mod/$wdmcsv
chmod 664 $CBP_EXPORT_DIR/river/$scenario/$mod/*.csv
# Remove message and h5 file to save space
echo "Cleaning up $h5file"
rm $h5file
rm message.wdm
# todo: add the call to run the river hsp2 summary script here
mv $seg'.wdm' $tree/tmp/wdm/river/$scenario/stream/ -f
