#!/bin/bash
# look for requested variable from a csh script
if [ -n "$1" ] ; then
  # we have been passed a scenario, find the control script variables
  # sed -r 's/set//' $CBP_ROOT/config/control/script/${1}.con
  while read cmd var eq val
  do
    if [[ $cmd == "set" ]]
    then
      declare -x "$var=$val"
      if [[ $2 == "all" ]]
      then
        echo "$var=$val"
      fi
      if [[ $2 == "$var" ]]
      then
        target_val=$val
        echo "$val"
      fi
    fi
  done < $confile
fi
