#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


echo "Trying to reproject $src_files for $ddate"
for originalFile in $src_files; do
  echo "Clearing pre-existing file ${originalFile}.repro.gtiff"
  if [ -e ${originalFile}.repro.gtiff ]; then
    echo "Clearing pre-existing file ${originalFile}.repro.gtiff"
    rm ${originalFile}.repro.gtiff
  fi
  extension="${originalFile##*.}"
  if [ "$extension" == "nc" ]; then
    echo "converting netcdf to getiff..."
    echo "gdalwarp $originalFile -t_srs EPSG:4326 -of \"gtiff\" \"${originalFile}.repro.gtiff\""
    #gdalwarp $originalFile -t_srs EPSG:4326 -of "gtiff" "${originalFile}.repro.gtiff"
  fi
done
