#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

nc_src_files=`ls $src_dir/*.nc`
if [ "$NLDAS2_GRB_TEMPLATE" == "" ]; then
  echo "ERROR: NLDAS2_GRB_TEMPLATE is not defined in met/${scenario}.con -- quitting." >> problem
  echo "ERROR: NLDAS2_GRB_TEMPLATE is not defined in met/${scenario}.con -- quitting."
  exit
fi
echo "Trying to reproject $nc_src_files for $ddate"
for originalFile in $nc_src_files; do
  extension="${originalFile##*.}"
  if [ "$extension" == "nc" ]; then
    # Extract precip layer
    # nc is hard to extract raster, so create a copy of this in grb format with all layers
    # Also, by converting this to the GRB format, it allows backwards compatibility with the P6 CBP wdm C++
    out_type='grb'
    file_base=${originalFile%.*}
    file_base=${file_base%.*}
    # the new nldas2 has file ending 020.nc, and the old had 002.grb
    # so we rewrite the file name here to 002 so there will only be one gtiff file (overwriting old)
    out_file="${file_base}.002."$out_type  # final file to import
    lyr_file="${file_base}.tif" # intermediate file - must have this  to accept layer setting, then convert
    if [ -f $out_file ]; then
      if [ "$NLDAS2_UPDATE_GRB" != "1" ]; then
        echo "Skipping existing grb file $out_file"
        continue
      fi
    fi
    rm $out_file
    rm $lyr_file 
    echo "Create GRB: gdal_create -if $NLDAS2_GRB_TEMPLATE -bands 11 $lyr_file"
    gdal_create -if $NLDAS2_GRB_TEMPLATE -bands 11 $lyr_file
    # clip 
    # Note: -srcband is always 1, since we've extracted the band already by specifying the band name like ":Tair"
    bnd=0
    for i in Tair Qair PSurf Wind_E Wind_N LWdown CRainf_frac CAPE PotEvap Rainf SWdown ;  do
    #for i in Rainf;  do
       bnd=$((bnd + 1))
       if [ "$i" != "Tair" ]; then
          echo "Running: gdalwarp NETCDF:\"$originalFile\":$i -t_srs EPSG:4326 $lyr_file -srcband 1 -dstband $bnd"
          gdalwarp NETCDF:"$originalFile":$i -t_srs EPSG:4326 $lyr_file -srcband 1 -dstband $bnd
       else
          kc_file="${file_base}.kc.tif"
          gdal_create -if $NLDAS2_GRB_TEMPLATE -bands 11 $kc_file
          echo "Running: gdalwarp NETCDF:\"$originalFile\":$i -t_srs EPSG:4326 $kc_file -srcband 1 -dstband $bnd"
          gdalwarp NETCDF:"$originalFile":$i -t_srs EPSG:4326 $kc_file -srcband 1 -dstband $bnd
          gdal_calc.py -A $kc_file --A_band=$bnd --calc="A - 273.0" --overwrite --outfile=$kc_file
          # perform Kelvin to Celsius translation
          echo "Converting Kelvin to Celsius"
          gdalwarp $kc_file -t_srs EPSG:4326 $lyr_file -srcband $bnd -dstband $bnd
          rm $kc_file
       fi
    done
    gdalwarp -of grib -t_srs EPSG:4326 $lyr_file $out_file
    rm $lyr_file 
    mv $out_file ${src_dir}/
  fi
done
