#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


echo "Trying to clip $src_files for $ddate"

for originalFile in $src_files; do
  if [ -e ${originalFile}${final_ext} ]; then
    echo "Clearing old version of ${originalFile}${final_ext} "
    rm ${originalFile}${final_ext}
  fi 

  echo "Reprojecting raster..."
  echo "gdalwarp -of \"gtiff\" -cutline $maskExtent -crop_to_cutline \"${originalFile}.repro.gtiff\" \"${originalFile}${final_ext}\" "
  gdalwarp -of "gtiff" -cutline $maskExtent -crop_to_cutline "${originalFile}.repro.gtiff" "${originalFile}${final_ext}"
  # these files will be deleted during the final step in case we need to do verification
done

#Clipping the raster: Use gdalwarp to crop to the cutline maskExtent.csv, which is a csv of the CBP regions 
	
