#!/bin/bash
# loads the met specific config
### ***************************
### This script converts the source
### Files into a geoTiff format
### with the name ofile
### All steps after this one in the 
### Workflow will expect this geoTiff
### ***************************

met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


echo "Trying to reproject $src_files for $ddate"
for originalFile in $src_files; do
  ofile=${originalFile}.$final_ext
  if [ -e $ofile ]; then
    echo "Clearing pre-existing file $ofile"
    rm $ofile
  fi
  echo "Converting raster to geoTiff..."
  echo "gdalwarp $originalFile -of \"gtiff\" \"$ofile\""
  gdalwarp $originalFile -of "gtiff" "$ofile"
done

