#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


echo "Checking whether to extract band $TS_BAND from $src_files for $ddate"
for originalFile in $src_files; do
  if [ "$TS_BAND" != "false" ]; then
    echo "Extracting $TS_BAND from ${originalFile}.repro.gtiff"
    cp "${originalFile}.repro.gtiff" "${originalFile}.allbands.gtiff"
    echo "cp \"${originalFile}.repro.gtiff\" \"${originalFile}.allbands.gtiff\""
    echo "gdal_translate -b $TS_BAND -of gtiff \"${originalFile}.allbands.gtiff\" \"$originalFile.repro.gtiff\" "
    gdal_translate -b $TS_BAND -of gtiff "${originalFile}.allbands.gtiff" "$originalFile.repro.gtiff"
    rm "${originalFile}.allbands.gtiff"
  fi
done
