#!/bin/bash

ddate=$1
datasource=$2
tempdir=$3

# loads the raster specific config
raster_config=`find_config raster.config`
if [ "$raster_config" = "" ]; then
  raster_config="$META_MODEL_ROOT/models/raster_met/raster.config"
fi
. $raster_config


# files to import can be inferred
base_dir=${config["basedir"]}
final_ext=${config["ext"]}
echo "Looking for geotiff files in $base_dir/$yr/$jday"

if [ "$datasource" != "nldas2" ]; then
    # single day files only,
    for fname in $import_files; do
        if [ -e $fname ]; then
            eval `gdalinfo $fname |grep TIFFTAG_DATETIME`
            if [ "$TIFFTAG_DATETIME" == "" ]; then
                TIFFTAG_DATETIME="${yr}-${mo}-${da}T00:00:00Z"
                echo "Setting TIFFTAG_DATETIME: gdal_edit.py $fname -mo \"TIFFTAG_DATETIME=${TIFFTAG_DATETIME}\""
                gdal_edit.py $fname -mo "TIFFTAG_DATETIME=${TIFFTAG_DATETIME}"
            fi
        fi
    done
else
    # This must be NLDAS2 with hourly files
    if [ -d "$base_dir/$yr" ]; then
        if [ -d "$base_dir/$yr/$jday" ]; then
            for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23; do 
                hr2digit=`printf %02d $i`
                hr4digit="${hr2digit}00"
                fname=`ls $src_dir/*.${hr4digit}.* | grep $final_ext`
                if [ "$fname" != "" ]; then
                    TIFFTAG_DATETIME="${yr}-${mo}-${da}T${hr2digit}:00:00Z"
                    # edit file meta data to set date time for later use
                    echo "Setting TIFFTAG_DATETIME: gdal_edit.py $fname -mo \"TIFFTAG_DATETIME=${TIFFTAG_DATETIME}\""
                    gdal_edit.py $fname -mo "TIFFTAG_DATETIME=${TIFFTAG_DATETIME}"
                fi
            done
        fi
    fi
fi