#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


echo "Trying to reproject for $ddate"
for originalFile in $src_files; do
  echo "cp ${originalFile}.repro.gtiff ${originalFile}.oproj.gtiff"
  cp "${originalFile}.repro.gtiff" "${originalFile}.oproj.gtiff"
  echo "Reprojecting raster..."
  echo "gdalwarp ${originalFile}.oproj.gtiff -t_srs EPSG:4326 -of gtiff ${originalFile}.repro.gtiff"
  gdalwarp ${originalFile}.oproj.gtiff -t_srs EPSG:4326 -of "gtiff" "${originalFile}.repro.gtiff"
  rm "${originalFile}.oproj.gtiff"
done
