#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


echo "Trying to clip $src_files for $ddate"

for originalFile in $src_files; do
  ofile="${originalFile}.${final_ext}"
  tfile=${originalFile}.tmp_clip.${final_ext}
  echo "Making a copy cp $ofile $tfile"
  cp $ofile $tfile
  rm $ofile
  echo "Clipping raster..."
  echo "gdalwarp -of \"gtiff\" -cutline $maskExtent -crop_to_cutline \"$tfile\" \"$ofile\" "
  gdalwarp -of "gtiff" -cutline $maskExtent -crop_to_cutline "$tfile" "$ofile"
  rm $tfile
  # these files will be deleted during the final step in case we need to do verification
done

#Clipping the raster: Use gdalwarp to crop to the cutline maskExtent.csv, which is a csv of the CBP regions 
	
