#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

# files to import can be inferred
echo "Looking for geotiff files in $base_dir/$yr/$jday"

if [ "$datasource" == "PRISM" ]; then
    # single day files only,
    echo "datasource is $datasource, checking $src_dir for $import_files"
    for fname in $import_files; do
        if [ -e $fname ]; then
            eval `gdalinfo $fname |grep TIFFTAG_DATETIME`
            TIFFTAG_DATETIME="${yr}-${mo}-${da}T${tz_hr}:00:00"
            echo "Setting TIFFTAG_DATETIME: $gdal_cdm $meta_switch \"TIFFTAG_DATETIME=${TIFFTAG_DATETIME}\" $fname"
            $gdal_cmd $meta_switch "TIFFTAG_DATETIME=${TIFFTAG_DATETIME}" $fname
        fi
    done
elif [ "$datasource" == "daymet" ]; then
    # single day files only,
    for fname in $import_files; do
        if [ -e $fname ]; then
            eval `gdalinfo $fname |grep TIFFTAG_DATETIME`
            #For dayment, we believe the datetime is the beginning of the 
            #timestamp, tstime. TIFFTAG_DATETIME is ultimately imported as the
            #end time, tsendtime. For this reason, we add one day to 
            #TIFFTAG_DATETIME for daymet
            tstime_start="${yr}-${mo}-${da}T${tz_hr}:00:00"
            TIFFTAG_DATETIME=`date -d "${tstime_start} 1 day" +'%Y-%m-%dT%H:%M:%S'`
            echo "Setting TIFFTAG_DATETIME: $gdal_cmd $fname $meta_switch \"TIFFTAG_DATETIME=${TIFFTAG_DATETIME}\""
            $gdal_cmd $fname $meta_switch "TIFFTAG_DATETIME=${TIFFTAG_DATETIME}"
        fi
    done
elif [ "$datasource" == "noaa_drought" ]; then
    # single day files only,
    for fname in $import_files; do
        if [ -e $fname ]; then
			eval `gdalinfo $fname |grep TIFFTAG_DATETIME`
            TIFFTAG_DATETIME="${yr}-${mo}-${da}T${tz_hr}:00:00"
            echo "Setting TIFFTAG_DATETIME: $gdal_cmd $fname $meta_switch \"TIFFTAG_DATETIME=${TIFFTAG_DATETIME}\""
            $gdal_cmd $fname $meta_switch "TIFFTAG_DATETIME=${TIFFTAG_DATETIME}"
        fi
    done
else
  # This is NLDAS2 with hourly files
  if [ -d "$base_dir/$yr" ]; then
    if [ -d "$base_dir/$yr/$jday" ]; then
      for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23; do 
        hr2digit=`printf %02d $i`
        hr4digit="${hr2digit}00"
        fname=`ls $src_dir/*.${hr4digit}.* | grep $final_ext`
        if [ "$fname" != "" ]; then
          echo "###################################"
          echo "Handling $fname"
          echo "###################################"
          TIFFTAG_DATETIME="${yr}-${mo}-${da}T${hr2digit}:00:00"
          # edit file meta data to set date time for later use
          echo "Setting TIFFTAG_DATETIME: $gdal_cmd $fname $meta_switch \"TIFFTAG_DATETIME=${TIFFTAG_DATETIME}\""
          $gdal_cmd $fname $meta_switch "TIFFTAG_DATETIME=${TIFFTAG_DATETIME}"
        fi
      done
    fi
  fi
fi
