#!/bin/bash
#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

echo "Cleaning up files for $ddate"

for originalFile in $src_files; do
  echo "Trying to remove: rm ${originalFile}.repro.gtiff"
  rm "${originalFile}.repro.gtiff"
done