#!/bin/bash
ddate=$1
datasource=$2

# loads the raster specific config
raster_config=`find_config raster.config`
if [ "$raster_config" = "" ]; then
  raster_config="$META_MODEL_ROOT/models/raster_met/raster.config"
fi
. $raster_config


echo "Cleaning up files for $ddate"

for originalFile in $src_files; do
  echo "Trying to remove: rm ${originalFile}.repro.gtiff"
  rm "${originalFile}.repro.gtiff"
done