#!/bin/bash
ddate=$1
datasource=$2
tempdir=$3

# loads the raster specific config
raster_config=`find_config raster.config`
if [ "$raster_config" = "" ]; then
  raster_config="$META_MODEL_ROOT/models/raster_met/raster.config"
fi
echo "Loading raster_config from $raster_config"
. $raster_config
cd $tempdir

#source $META_MODEL_ROOT/sh/addRasterToDBase2.sh
if [ "$import_files" == "" ]; then
  echo "Import files not found in $src_dir. Exiting"
  exit
else
  echo "Importing file converted from $src_dir ..."
  if [ - e "raster_list.txt" ]; then 
    rm raster_list.txt
  fi
  touch raster_list.txt
  for met_file in $import_files; do
    # set the variable TIFFTAG_DATETIME from meta-data
    eval `gdalinfo $met_file |grep TIFFTAG_DATETIME`
    if [ "$TIFFTAG_DATETIME" == "" ]; then
      echo "Could not find TIFFTAG_DATETIME in meta-data for $met_file ($TIFFTAG_DATETIME)"
      echo "Could not find TIFFTAG_DATETIME in meta-data for $met_file" > problem
      exit
    fi
    TZ=${config["TZ"]}
    echo "TIMESTAMP HANDLING: tstime='TZ=\"$TZ\" date -d \"$TIFFTAG_DATETIME\" +'%s''"
    tstime=`TZ="$TZ" date -d "$TIFFTAG_DATETIME" +'%s'`
    # attach a property to the dh_timeseries_weather record pointing to the raster file.
    img_varkey='dh_image_file'
    echo "$tstime\t$datasource,$extent_hydrocode,$extent_ftype,$img_varkey,$met_file" >> raster_list.txt
  done
  cmd="Rscript $META_MODEL_ROOT/scripts/met/met_store_info.R $ddate $datasource $extent_hydrocode $extent_ftype $img_varkey $met_file"    
  echo "Running: $cmd"
  eval $cmd

fi
