#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

cd $tempdir

#source $META_MODEL_ROOT/sh/addRasterToDBase2.sh
if [ "$import_files" == "" ]; then
  echo "Import files not found in $src_dir. Exiting"
  exit
else
  echo "Importing file converted from $src_dir ..."
  if [ -e "raster_list.txt" ]; then 
    rm raster_list.txt
  fi
  touch raster_list.txt
  for met_file in $import_files; do
    # set the variable TIFFTAG_DATETIME from meta-data
    eval `gdalinfo $met_file |grep TIFFTAG_DATETIME`
    if [ "$TIFFTAG_DATETIME" == "" ]; then
      echo "Could not find TIFFTAG_DATETIME in meta-data for $met_file ($TIFFTAG_DATETIME)"
      echo "Could not find TIFFTAG_DATETIME in meta-data for $met_file" > problem
      exit
    fi
    echo "TIMESTAMP HANDLING: tstime='TZ=\"$TZ\" date -d \"$TIFFTAG_DATETIME\" +'%s''"
    tstime=`TZ="$TZ" date -d "$TIFFTAG_DATETIME" +'%s'`
    # attach a property to the dh_timeseries_weather record pointing to the raster file.
    img_varkey='dh_image_file'
    echo "$tstime\t$datasource,$extent_hydrocode,$extent_ftype,$img_varkey,$met_file" >> raster_list.txt
  done

fi
