#!/bin/csh
# Run post-process extract routine
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
cd $tempdir

set hydrcsv=${seg}_hydr'.csv'
set divrcsv=${seg}_divr'.csv'
echo "Notice: Rscript $MODEL_ROOT/run/export/join_col.R $hydrcsv $divrcsv values divr_cfs header day"
Rscript $MODEL_ROOT/run/export/join_col.R $hydrcsv $divrcsv "values" "divr_cfs" "header" "day"

set divacsv=${seg}_diva'.csv'
echo "Notice: Rscript $MODEL_ROOT/run/export/join_col.R $hydrcsv $divrcsv values diva_cfs header day"
Rscript $MODEL_ROOT/run/export/join_col.R $hydrcsv $divacsv "values" "diva_cfs" "header" "day"

set pscsv=${seg}_ps'.csv'
echo "Notice: Rscript $MODEL_ROOT/run/export/join_col.R $hydrcsv $pscsv values ps_afd header day"
Rscript $MODEL_ROOT/run/export/join_col.R $hydrcsv $pscsv "values" "ps_afd" "header" "day"
