#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3

set tempbase=`basename $tempdir`
install -d $MODEL_ROOT/tmp/$user-scratch
cd $MODEL_ROOT/tmp/$user-scratch
rm -Rf $tempbase

if ( ! -d $tempdir ) then
  mkdir $tempdir
endif
