#!/bin/bash
scenario=$1
segment=$2
tmp_dir=$3

echo "cd $tmp_dir"

cd $tmp_dir
clean=1
echo "Run: cbp run_rug.csh $scenario $segment $MODEL_ROOT"
$MODEL_ROOT/run/standard/run_rug.csh $scenario $segment $MODEL_ROOT
