#!/bin/csh

# Get params from comand arguments
set model=$1
set scenario=$2
set segment=$3
if (${#argv} >= 4) then
  set work_path=$4
else
  set work_path=`./plugins/$model/get_work_path`
endif
echo "Model work_path = $work_path"

# @todo: handle command line switches for glaf arguments
# -i, --IGNORE_PROBLEMS : set environment variable IGNORE_PROBLEMS
if (! $?IGNORE_PROBLEMS) then
  setenv IGNORE_PROBLEMS 0
endif
# Set up which modules to run
# probably should NOT hard code these, instead 
# relying on the model to configure this for us
set modules = "all"
if (${#argv} >= 5) then
  set modules = ($5:as/,/ /)
endif
if ( $modules == "all" ) then
  set modules = ( land river )
endif

# Set Up Run Steps
# see above, maybe this should not be hard-coded?
set run_steps = ( prep run link analyze )
if (${#argv} >= 6) then
  set run_steps = ($6:as/,/ /)
endif
if ( $run_steps[1] == "all" ) then
  set run_steps = ( prep run link analyze )
endif
echo $run_steps

# Set up which scripts to run in each step
# this will end up producing errors if misconfigured, and is seldom needed
set script = "all"
if (${#argv} >= 7) then
  set script = ($7:as/,/ /)
endif
