#!/bin/bash

. $META_MODEL_ROOT/models/om/om.config
runid=$scenario

c1_script="/opt/model/om/R/summarize/usgs_weighted.R"
# We use "scenario_name" below since it has the prefix "runid_" for dh storage
echo "Sumarizing: Rscript $c1_script $usgs_pid $segment $scenario $usgs_out_file"
Rscript $c1_script $usgs_pid $segment $scenario $usgs_out_file

