#!/bin/bash
# loads the args, the raster specific config and change to tempdir
wdm_config=`find_config wdm.config`
if [ "$wdm_config" = "" ]; then
  wdm_config="$META_MODEL_ROOT/models/raster_met/wdm/wdm.config"
fi
. $wdm_config

if [[ $MET_PROCESS_METHOD != "cbp6" ]]; then
  exit
fi

# TBD:
# for re-do grid summary (time-consuming)
# grid2land.sh $data_start $data_end $base_dir $outdir $i
# a2l_one $sdatemins $edatemins $outdir $lsegdir $i
# LongTermAvgRNMax $lsegdir/met2date $lsegdir/RNMax 1 $i
