#!/bin/bash
# loads the args, the raster specific config and change to tempdir
wdm_config=`find_config wdm.config`
if [ "$geo_config" = "" ]; then
  wdm_config="$META_MODEL_ROOT/models/raster_met/wdm/wdm.config"
fi
. $wdm_config

# call Rscript to format data as WDM importable
echo "Call: Rscript $META_MODEL_ROOT/scripts/wdm/csv_export_wdm_format.R $COVERAGE_PRECIP_FILE $COVERAGE_WDM_CSV precip_in hour"
Rscript $META_MODEL_ROOT/scripts/wdm/csv_export_wdm_format.R $COVERAGE_PRECIP_FILE $COVERAGE_WDM_CSV precip_in hour
