#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
set tree = $MODEL_ROOT

# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
echo "Changing to  $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR"
cd $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR

######## Apply SPARROW Reservoir (Type II) Efficiency
echo $scenario $segment 1 | $tree/code/bin/reservoir_type_II.exe
