#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
set tree=$MODEL_ROOT
source $MODEL_ROOT/config/control/script/${scenario}.con
echo "Export source org: cd $tempdir"
cd $tempdir

echo $scenario $segment 1 | $tree/code/bin/scrorg.exe
if ( -e problem ) then
   cat problem
   exit
endif
# in the old scripts these "cp" were "mv"
# but this makes little sense if we are just going to delete the temp
# directory after a successful run. So, we use copy instead
cp $segment'_scr.out' $tree/output/hspf/river/out/$scenario/
cp $segment'.out' $tree/output/hspf/river/out/$scenario/
cp $segment'.ech' $tree/output/hspf/river/ech/$scenario/
cp $segment'.wdm' $tree/tmp/wdm/river/$scenario/stream/
