#!/bin/csh
# THis exports hydro dat from the hdf5 to a CSV for import into the river wdm
# this is doen here because the sediment routine needs to have he hydro data 
# in the WDM to complete.  It is later used by the next downstream
# do NOT be tempted to move this to "link", as the sediment will fail!
set scenario=$1
set segment=$2
set seg = $segment
set tempdir=$3
set tree = $MODEL_ROOT
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config

echo "Locating: cd $tempdir"
cd $tempdir

echo "SETTING MODEL STATUS"
# set vars here for brevity of code
set flag=0
set msg="Model run execution complete."
set ftype=$RIVER_FTYPE
set ver=$MODEL_VERSION_CODE
echo "Notice: Rscript $META_MODEL_ROOT/scripts/rest/set_model_status.R $seg $scenario $ver $ftype $flag $msg "
Rscript $META_MODEL_ROOT/scripts/rest/set_model_status.R $seg $scenario $ver $ftype $flag "$msg"
