#!/bin/csh
echo "Loading model configuration"
if (! $?MODEL_ROOT) then
  echo "Variable MODEL_ROOT is undefined.  Exiting."
  exit
endif
# Load defaults
# Put whatever you need in here to be available to script pieces
# Use csh so the meta source protocol works
echo "model_config finished."
# to create a custom list of modules/run_steps, do this:
# these will later be used if user submits "all" as list of modules to run
# set all_modules = [ land river ]
# set all_run_steps = [ prep run link ]
# Define modules to loop through
set modules='mllr'
