#!/bin/csh
echo "Loading model configuration"
#if (! $?MODEL_ROOT) then
#  echo "Variable MODEL_ROOT is undefined.  Exiting."
#  exit
#endif
# what is the date?
# what is the julian day?
# what is the base file name?
# do we have a feature hydrocode?
# which database host?
# Define modules to loop through
set all_modules = ( mllr )
set all_run_steps = ( download analyze )
set MODEL_BIN = $META_MODEL_ROOT
echo "model_config finished."
