#!/bin/csh
set scenario=$1
set segment=$2
set tmp_dir=$3

set tree = $CBP_ROOT

########## make stream wdms: copy the eos wdm then add upstream to it. ******

if (!(-e $tree/tmp/wdm/river/$scenario/eos/$seg'.wdm')) then
  echo 'Problem in river' > problem
  echo ' could not find eos wdm: ' >> problem
  echo  $tree/tmp/wdm/river/$scenario/eos/$seg'.wdm' >> problem
  echo ' check that etm ran for segment ' $seg >> problem
  cat problem
  exit
endif
echo "Copying river WDM $tree/tmp/wdm/river/$scenario/eos/$seg'.wdm' $seg'.wdm'"
cp -v $tree/tmp/wdm/river/$scenario/eos/$seg'.wdm' $seg'.wdm'
echo $scenario, $seg | $tree/code/bin/stream_wdm.exe
if (-e problem) then
  echo 'Problem adding upstream segments to wdm file, segment ',$seg
  cat problem
  exit
endif
