#!/bin/csh
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3


source $MODEL_ROOT/config/control/script/${scenario}.con
if (! $?HSP_EXEC) then       
  echo "hsp_exec variable is undefined.  Check the scenario config file $MODEL_ROOT/config/control/script/${scenario}.con"
  echo "hsp_exec variable is undefined." > problem
  exit
else
echo "Workspace: cd $tempdir"
cd $tempdir

set inp = $MODEL_ROOT/tmp/uci/river/$scenario/$seg'.uci'
cp -vip $inp .
set inp = $seg'.uci'
set h5 = $seg'.h5'
if (!(-e $inp)) then
  echo 'HSPF UCI for segment ' $seg ' named'
  echo $inp 'does not exist'
  exit
endif

$HSP_EXEC import_uci $inp $h5
