#!/bin/csh
set scenario=$1
set segment=$2
set tmp_dir=$3

source $CBP_ROOT/config/control/script/${scenario}.con
if (! $?HSP_EXEC) then       
  echo "hsp_exec variable is undefined.  Check the scenario config file $CBP_ROOT/config/control/script/${scenario}.con"
  echo "hsp_exec variable is undefined." > problem
  exit
else
cd $CBP_ROOT/$MY_HOME/$SCRIPT_DIR

set inp = $CBP_ROOT/tmp/uci/river/$scenario/$seg'.uci'
cp -vip $inp .
set inp = $seg'.uci'

if (!(-e $inp)) then
  echo 'HSPF UCI for segment ' $seg ' named'
  echo $inp 'does not exist'
  exit
endif

echo $inp | $HSP_EXEC

# @todo: put in run execution checks like normal HSPF has
