#!/bin/csh
set scenario=$1
set segment=$2
set tmp_dir=$3
set tree = $CBP_ROOT
source $CBP_ROOT/config/control/script/${scenario}.con
echo "Changing to  $CBP_ROOT/$MY_HOME/$SCRIPT_DIR"
cd $CBP_ROOT/$MY_HOME/$SCRIPT_DIR

######## Apply SPARROW Reservoir (Type II) Efficiency
echo $scenario $seg 1 | $tree/code/bin/reservoir_type_II.exe
