#!/bin/csh
set scenario=$1
set segment=$2
set tmp_dir=$3
set tree=$CBP_ROOT
source $CBP_ROOT/config/control/script/${scenario}.con
cd $CBP_ROOT/$MY_HOME/$SCRIPT_DIR

echo $scenario $seg 1 | $tree/code/bin/scrorg.exe
if ( -e problem ) then
   cat problem
   exit
endif
mv $seg'_scr.out' $tree/output/hspf/river/out/$scenario/
mv $seg'.out' $tree/output/hspf/river/out/$scenario/
mv $seg'.ech' $tree/output/hspf/river/ech/$scenario/
mv $seg'.wdm' $tree/tmp/wdm/river/$scenario/stream/
rm ps_sep_div_ams_$scenario'_'$seg'.wdm'
