#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
set tree=$MODEL_ROOT
source $MODEL_ROOT/config/control/script/${scenario}.con
echo "Export source org: cd $tempdir"
cd $tempdir

echo $scenario $segment 1 | $tree/code/bin/scrorg.exe
if ( -e problem ) then
   cat problem
   exit
endif
mv $segment'_scr.out' $tree/output/hspf/river/out/$scenario/
mv $segment'.out' $tree/output/hspf/river/out/$scenario/
mv $segment'.ech' $tree/output/hspf/river/ech/$scenario/
mv $segment'.wdm' $tree/tmp/wdm/river/$scenario/stream/
rm ps_sep_div_ams_$scenario'_'$segment'.wdm'
