#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3

set tempbase=`basename $tempdir`
cd $MODEL_ROOT/tmp/
echo "cd $MODEL_ROOT/tmp/"

rm -Rf $tempbase/*

if ( ! -d $tempdir ) then
  echo "Creating $tempdir"
  mkdir $tempdir
endif

# call make_directories if not already done
# should do better than to just assume "for" is 
# always going to be a valid land use name but for now
# we go with it
source $MODEL_ROOT/run_bhatt/fragments/set_landuse
set onelu=$perlnds[1]
echo "Checking for existence of $MODEL_ROOT/tmp/uci/land/$onelu/$scenario"
if ( ! -d "$MODEL_ROOT/tmp/uci/land/$onelu/$scenario" ) then
  echo "Land directories not set up, calling make_land_directories.csh $scenario"
  cd $MODEL_ROOT/run/standard/
  csh make_land_directories.csh $scenario
endif

