#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
set seg = $segment

source $MODEL_ROOT/config/control/script/${scenario}.con
echo "Changing to $tempdir"
#cd $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR
#cd $tempdir

echo "Calling: cbp run_land_oneseg.csh $scenario $segment $tempdir"
#$MODEL_ROOT/run/standard/run_land_oneseg.csh $scenario $segment $tempdir
cbp run_land_oneseg.csh $scenario $segment 
