#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3

IFS='_' read usgs_gage riverseg <<< "$segment"
ftype=`cbp get_config $scenario script RIVER_FTYPE`
hydrocode_prefix=`cbp get_config $scenario script RIVER_PREFIX`
hydrocode="${hydrocode_prefix}_${segment}"
USGS_MODEL_CODE=`cbp get_config $scenario script USGS_MODEL_CODE`
echo "Running: Rscript make_usgs_gage_model.R $segment $hydrocode, $ftype, \"$USGS_MODEL_CODE\", $MODEL_VERSION_CODE"
#Rscript make_usgs_gage_model.R $segment $hydrocode, $ftype, "$USGS_MODEL_CODE", "$MODEL_VERSION_CODE"
