#!/bin/csh
set scenario=$1
set segment=$2
set seg=$segment # backwards compat
set tempdir=$3

set tree = $MODEL_ROOT
# load all model config
source $META_MODEL_ROOT/models/$MODEL/model_config 

## Move to the execution directory
cd $tempdir

########### Handleconfluence
if (-e confluencefile) then
  rm confluencefile
endif
echo $seg $scenario | $tree/code/bin/getconfluence.exe
if (-e confluencefile) then
  chmod 777 confluencefile
  ./confluencefile
  rm confluencefile
  echo $scenario, $seg | $tree/code/bin/confluence.exe
  if (-e problem) then
    echo 'Problem with confluence program'
    cat problem
    exit
  endif
  mv *_0003.wdm $tree/tmp/wdm/river/$scenario/stream/
endif

