#!/bin/csh
# Run post-process extract routine
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
cd $tempdir

echo "Exporting HYDR data for $seg"
set ds="/RESULTS/RCHRES_R001/HYDR/table"
set mod="hydr"
set csvfile = ${seg}_hydr'.csv'
set h5file = ${seg}.h5
echo "Notice: Rscript $MODEL_ROOT/run/export/export_hsp_h5.R $h5file $csvfile $ds"
Rscript $MODEL_ROOT/run/export/export_hsp_h5.R $h5file $csvfile $ds
Run conversion script to add Qout and other derived/alias columns
echo "Notice (unit conversions): Rscript $MODEL_ROOT/run/export/hsp_hydr_conversion.R $csvfile"
Rscript $MODEL_ROOT/run/export/hsp_hydr_conversion.R $csvfile 
# Prep outflow data for export to river wdm
set wdmcsv = ${seg}_rovol'.csv'
echo "Notice: Rscript $MODEL_ROOT/run/export/csv_export_wdm_format.R $csvfile $wdmcsv ROVOL"
Rscript $MODEL_ROOT/run/export/csv_export_wdm_format.R $csvfile $wdmcsv ROVOL
# Push ROVOL into wdm
# copy here cause it is hardto send these paths to wdm_insert_one, need escape?
cp /usr/local/lib/hspf/message.wdm ./
echo ${seg}.wdm $wdmcsv 111 1 w message.wdm | wdm_insert_one
# move all files to the model data archive
cp $csvfile $CBP_EXPORT_DIR/river/$scenario/$mod/ -f
chgrp $MODEL_FILES_GROUP $CBP_EXPORT_DIR/river/$scenario/$mod/$csvfile
chmod 664 $csvfile
cp $wdmcsv $CBP_EXPORT_DIR/river/$scenario/$mod/ -f
chgrp $MODEL_FILES_GROUP $CBP_EXPORT_DIR/river/$scenario/$mod/$wdmcsv
chmod 664 $wdmcsv
# Remove message and h5 file to save space
#echo "Cleaning up $h5file"
#rm $h5file
#rm message.wdm
# export the flow data
if ( $?START_YEAR ) then
  echo "echo ${seg}.wdm,$START_YEAR,$END_YEAR,111 | wdm2text"
  echo "${seg}.wdm,$START_YEAR,$END_YEAR,111" | wdm2text
  cp $seg'_0111.csv' $CBP_EXPORT_DIR/river/$scenario/stream/ -f
endif
cp $seg'.wdm' $MODEL_ROOT/tmp/wdm/river/$scenario/stream/ -f

