#!/bin/csh
# Push data back into WDM file for the sediment routine to use it in the next step of run
# also this satisfies the export for the next downstream WDM
set scenario=$1
set segment=$2
set seg = $segment
set tempdir=$3
#source $MODEL_ROOT/config/control/script/${scenario}.con
source $META_MODEL_ROOT/models/$MODEL/model_config
set tree = $MODEL_ROOT
cd $tempdir

set csvfile = $tempdir/${seg}_hydr.csv
set cols = ( OVOL3 )
set dsns = ( 111 )
set num = $#cols
set i = 1
while ( $i <= $num )
  set col = $cols[$i]
  set dsn = $dsns[$i]
  # Prep outflow data for export to river wdm
  set wdmcsv = ${seg}_${col}'.csv'
  echo "Notice: Rscript $META_MODEL_ROOT/scripts/wdm/csv_export_wdm_format.R $csvfile $wdmcsv $col hour"
  Rscript $META_MODEL_ROOT/scripts/wdm/csv_export_wdm_format.R $csvfile $wdmcsv $col "hour"
  # Push into wdm
  # copy here cause it is hardto send these paths to wdm_insert_one, need escape?
  cp /usr/local/lib/hspf/message.wdm ./
  echo ${seg}.wdm $wdmcsv $dsn 1 w message.wdm | wdm_insert_one
  @ i++
end
cp $segment'.wdm' $tree/tmp/wdm/river/$scenario/stream/

# We used to have this, but I think it is superfluous?
# export the flow data
#if ( $?START_YEAR ) then
#  echo "echo ${seg}.wdm,$START_YEAR,$END_YEAR,111 | wdm2text"
#  echo "${seg}.wdm,$START_YEAR,$END_YEAR,111" | wdm2text
#  cp $seg'_0111.csv' $CBP_EXPORT_DIR/river/$scenario/stream/ -f
#endif
