#!/bin/bash
# loads the args, the raster specific config and change to temp dir
amalgamate_config=`find_config amalgamate.config`
if [ "$amalgamate_config" = "" ]; then
  amalgamate_config="$META_MODEL_ROOT/models/raster_met/amalgamate/amalgamate.config"
fi
. $amalgamate_config

#Create a best-fit raster based on the amalgamate scenario and the background varkey
#First, Grab the USGS full drainage geometries/coverages and assign ratings to inicate best 
#performing precip dataset
#Next, Union the best rated datasets together picking the last selected pixel value. Since the data is sorted by drainage area, 
#upstream areas will populate after larger, downstream coverages
#Then Use a full union to create a column with the amalgamateUnion raster and the nldasFulLDayResamp raster
#Then, union the rasters to get a raster in which the "background" is the nldasFullDayResamp and everything else is 
#the best fit raster
bestraster_sql="
\\set tsstartin '$TS_START_IN' \n
\\set tsendin '$TS_END_IN' \n
\\set resample_varkey '$RESAMPLE_VARKEY' \n
\\set amalgamate_scenario '$AMALGAMATE_SCENARIO' \n
\\set background_varkey '$BACKGROUND_VARKEY' \n
\\set ratings_varkey '$RATINGS_VARKEY' \n
\\set coverage_bundle '$COVERAGE_BUNDLE' \n
\\set coverage_ftype '$COVERAGE_FTYPE' \n
select hydroid as covid from dh_feature
where hydrocode = '$EXTENT_HYDROCODE' and bundle = '$EXTENT_BUNDLE'
AND ftype = '$EXTENT_FTYPE' \\gset \n

SELECT scen.pid as scenariopid \n
FROM dh_properties as scen \n
LEFT JOIN dh_properties as model \n
ON model.pid =  scen.featureid \n
LEFT JOIN dh_feature as feat \n
on feat.hydroid = model.featureid \n
WHERE feat.hydroid = :'covid'  \n
and scen.propname = :'amalgamate_scenario' \\gset \n

SELECT hydroid AS ratings FROM dh_variabledefinition WHERE varkey = :'ratings_varkey' \\gset \n

DELETE FROM dh_timeseries_weather \n
WHERE varid = :ratings  \n
AND entity_type = 'dh_properties' \n
AND tstime = :tsstartin \n
AND tsendtime = :tsendin \n
AND featureid = :scenariopid; \n
\n

WITH usgsCoverage as (  \n
	SELECT f.hydroid,f.hydrocode,  \n
		ts.tstime,  \n
		ts.tsendtime,  \n
		ts.tsvalue as dataID,  \n
		bestVarkey.varkey as dataVarkey,  \n
		ST_AREA(f.dh_geofield_geom) as covArea  \n
		,f.dh_geofield_geom as dh_geofield_geom  \n
	FROM dh_feature_fielded as f  \n
	LEFT JOIN dh_properties AS model  \n
	ON model.featureid = f.hydroid  \n
	LEFT JOIN dh_properties as scen  \n
	ON scen.featureid = model.pid  \n
	LEFT JOIN dh_timeseries as ts  \n
	ON ts.featureid = scen.pid  \n
	LEFT JOIN dh_variabledefinition as v  \n
	on v.hydroid = ts.varid  \n
	LEFT JOIN dh_variabledefinition as bestVarkey  \n
	on bestVarkey.hydroid = ts.tsvalue  \n
	WHERE f.bundle = :'coverage_bundle' AND f.ftype = :'coverage_ftype'  \n
		AND model.propname ilike '%${MET_MODEL_VERSION}'  \n
		AND v.varkey = :'ratings_varkey'  \n
		AND scen.propname = :'amalgamate_scenario'  \n
		AND ts.tsendtime = :'tsendin'  \n
	ORDER BY covArea --DESC  \n
)  \n
,backgroundTemplate as (  \n
	SELECT ST_SetValue(rt.rast, 1, ST_ConvexHull(rt.rast), v.hydroid) as rast  \n
	FROM dh_variabledefinition as v  \n
	LEFT JOIN (select rast from raster_templates where varkey = :'resample_varkey') as rt  \n
	ON 1 = 1  \n
	WHERE v.varkey = :'background_varkey'  \n
)  \n
,bestData as (  \n
	SELECT cov.hydroid,cov.hydrocode,cov.tstime,cov.tsendtime,  \n
	st_clip( \n
		ST_SetValue( \n
			rt.rast,1,  \n
			cov.dh_geofield_geom,  \n
			cov.dataID \n
		), cov.dh_geofield_geom \n
	) as rast \n
	FROM usgsCoverage as cov  \n
	LEFT JOIN (select rast from raster_templates where varkey = :'resample_varkey') as rt  \n
	ON 1 = 1  \n
	WHERE cov.dataID = 1459
	LIMIT 3
)  \n
,amalgamateUnion as (  \n
	SELECT ST_union(rast,'LAST') as rast  \n
	FROM bestData  \n
)  \n
,finalRast as (  \n
	SELECT ST_union(fullUnion.rast,'LAST') as rast  \n
	FROM (  \n
	--	SELECT rast FROM backgroundTemplate  \n
	--	UNION ALL  \n
		SELECT rast FROM amalgamateUnion   \n
	) as fullUnion  \n
)  \n
insert into dh_timeseries_weather (tstime,tsendtime, featureid, entity_type, rast, bbox, varid) \n
select :tsstartin,:tsendin,:scenariopid,'dh_properties',  \n
fr.rast, ST_ConvexHull(fr.rast), :ratings  \n
FROM finalRast as fr
RETURNING tid;
"

# turn off the expansion of the asterisk
set -f
#Delete previous dh_timeseries entries
echo "Writing sql insert to $VARID_SQL_FILE"
echo $bestraster_sql
echo -e $bestraster_sql > $VARID_SQL_FILE 
cat $VARID_SQL_FILE | psql -h $db_host $db_name
echo "Finshed running query."
