#!/bin/bash
# loads the args, the raster specific config and change to temp dir
amalgamate_config=`find_config amalgamate.config`
if [ "$amalgamate_config" = "" ]; then
  amalgamate_config="$META_MODEL_ROOT/models/raster_met/amalgamate/amalgamate.config"
fi
. $amalgamate_config

SCENARIOS_TO_RANK_CLEAN=`echo "${SCENARIOS_TO_RANK}" | sed -e "s/^'//;s/'$//;s/','/ /g"`

#Iterate through scenarios identified in $SCENARIOS_TO_RANK_CLEAN and amalgamate a best fit precip raster
i=FALSE
for j in $SCENARIOS_TO_RANK_CLEAN;
do
	#Use amalgamate.sh to amalgamate the raster, one dataset at a time
    amalgamate.sh $TS_START_IN $TS_END_IN $RESAMPLE_VARKEY $AMALGAMATE_SCENARIO $AMALGAMATE_VARKEY $RATINGS_VARKEY $COVERAGE_BUNDLE $COVERAGE_FTYPE $SCENARIO_NAME $EXTENT_HYDROCODE $EXTENT_BUNDLE $EXTENT_FTYPE $AMALGAMATE_SQL_FILE $i $db_host $db_name
	i=TRUE
done



for j in $SCENARIOS_TO_RANK_CLEAN;
do
echo $j
done