#!/bin/csh
# Push data back into WDM file for the sediment routine to use it in the next step of run
# also this satisfies the export for the next downstream WDM
set scenario=$1
set segment=$2
set seg = $segment
set tempdir=$3
#source $MODEL_ROOT/config/control/script/${scenario}.con
source $META_MODEL_ROOT/models/$MODEL/model_config
set tree = $MODEL_ROOT
cd $tempdir

# grab the eos WDM
mv $tree/tmp/wdm/river/$scenario/eos/${seg}.wdm ./

# export the flow data from DSN11 which should only be runoff since the ETM just ran
# but stream_wdm.exe doesn't add the upstream flow until later in the "run" portion of this flow
set wdmcsv = ${seg}_0011.csv
if ( $?START_YEAR ) then
  echo "echo ${seg}.wdm,$START_YEAR,$END_YEAR,11 | wdm2text"
  echo "${seg}.wdm,$START_YEAR,$END_YEAR,11" | wdm2text
  cp $wdmcsv $CBP_EXPORT_DIR/river/$scenario/stream/$seg'_0010.csv' -f
else
  echo "Problem could not locate model START_YEAR and END_YEAR" > problem
  exit
endif

echo "Adding DSN 11 to WDM as DSN 10"
cp /usr/local/lib/hspf/message.wdm ./
echo "echo ${seg}.wdm $wdmcsv 10 1 w message.wdm | wdm_insert_one"
echo ${seg}.wdm $wdmcsv 10 1 w message.wdm | wdm_insert_one

# now copy the eos wdm back
cp ${seg}.wdm $tree/tmp/wdm/river/$scenario/eos/

echo "Finished Adding runoff data to DSN 10"
