#!/bin/bash
# loads the args, the raster specific config and change to tempdir
om_config=`find_config om.config`
if [ "$om_config" = "" ]; then
  om_config="$META_MODEL_ROOT/models/om/om.config"
fi
. $om_config
# NOTE: segment in this module is the elementid of the om entity to be migrated TO

cd /var/www/html/om
echo "Calling: Rscript /opt/model/om/R/set_element.R pid $segment"
Rscript /opt/model/om/R/set_element.R pid $segment
