#!/bin/bash
# loads the args, raster & geo specific config AND CHANGE TO TEMPDIR
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config
# BEGIN - actually loading local data

echo "Importing regression coefficients for ${coverage} to ${db_host}"

echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/usgs_post_regression.R \"$GAGEID\" $COVERAGE_BUNDLE \"$COVERAGE_FTYPE\" \"$MODEL_VERSION\" \"$SCENARIO_PROPNAME\" \"${BASEFLOW_REGRESSION_DF}\""
Rscript $META_MODEL_ROOT/scripts/usgs/usgs_post_regression.R "$GAGEID" "$COVERAGE_BUNDLE" "$COVERAGE_FTYPE" $MODEL_VERSION $SCENARIO_PROPNAME $BASEFLOW_REGRESSION_DF
