#!/bin/bash
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config

echo "Importing QC metrics for ${coverage} to ${db_host}"

echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/usgs_post_QC.R \"$GAGEID\" $COVERAGE_BUNDLE \"$COVERAGE_FTYPE\" \"$MODEL_VERSION\" NA \"${NUMEVENTS_QC_DF}\" \"${GAGE_QC_DF}\" \"${WSHED_SLOPE_DF}\""
Rscript $META_MODEL_ROOT/scripts/usgs/usgs_post_QC.R "${GAGEID}" "${COVERAGE_BUNDLE}" "${COVERAGE_FTYPE}" "${MODEL_VERSION}" NA "${NUMEVENTS_QC_DF}" "${GAGE_QC_DF}" "${WSHED_SLOPE_DF}"
