#!/bin/bash
# loads the args, the raster specific config and change to temp dir
amalgamate_config=`find_config amalgamate.config`
if [ "$amalgamate_config" = "" ]; then
  amalgamate_config="$META_MODEL_ROOT/models/raster_met/amalgamate/amalgamate.config"
fi
. $amalgamate_config

# This only runs if we are making a scenario into it's own varkey and migrating it to the domain converage feature
# instead of being attached to the property
if [ "$PROMOTE_DATASET" != "1" ]; then
  echo "PROMOTE_DATASET not set. Will not make dataset into feature based dataset. Exiting." 1>&2
  exit
fi


