#!/bin/bash

. $META_MODEL_ROOT/models/om/om.config
runid=$scenario
pid=`Rscript $META_MODEL_ROOT/scripts/rest/get_feature_model.R $segment $scenario $model_version $R`



object_class=`Rscript $META_MODEL_ROOT/scripts/rest/get_property.R dh_properties $pid object_class propcode`
custom1=`Rscript $META_MODEL_ROOT/scripts/rest/get_property.R dh_properties $pid custom1 propcode`
custom2=`Rscript $META_MODEL_ROOT/scripts/rest/get_property.R dh_properties $pid custom2 propcode`

echo "Sumarizing container: $META_MODEL_ROOT/scripts/om/summarize_element $elid $runid $DRUPAL_ROOT"
$META_MODEL_ROOT/scripts/om/summarize_element $elid $runid $DRUPAL_ROOT

