#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

echo "Importing data from ${datasource}"
echo "DB_FORCE_OVERWRITE = $DB_FORCE_OVERWRITE"
if [ -z ${DB_FORCE_OVERWRITE+x} ]; then 
  DB_FORCE_OVERWRITE=0
fi

#source $META_MODEL_ROOT/sh/addRasterToDBase2.sh
if [ "$import_files" == "" ]; then
  echo "Import files not found in $src_dir. Exiting"
  exit
else
  echo "Importing file converted from $src_dir ..."
  for met_file in $import_files; do
    # set the variable TIFFTAG_DATETIME from meta-data
    eval `gdalinfo $met_file |grep TIFFTAG_DATETIME`
    if [ "$TIFFTAG_DATETIME" == "" ]; then
      echo "Could not find TIFFTAG_DATETIME in meta-data for $met_file ($TIFFTAG_DATETIME)"
      echo "Could not find TIFFTAG_DATETIME in meta-data for $met_file" > problem
      exit
    fi
    echo "TIMESTAMP HANDLING: tstime='TZ=\"$TZ\" date -d \"$TIFFTAG_DATETIME\" +'%s''"
    tsendtime=`TZ="$TZ" date -d "$TIFFTAG_DATETIME" +'%s'`
    tstime=$((tsendtime - dt))
    cmd="$MET_SCRIPT_PATH/sh/met_raster2db.sh "${datasource}" $met_file $tstime $tsendtime "${entity_type}" "${varkey}" "${extent_hydrocode}" $db_name $db_host $DB_FORCE_OVERWRITE"
    echo "Running: $cmd"
    eval $cmd
  done
fi
