#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

echo "Importing data from ${datasource}"
echo "DB_FORCE_OVERWRITE = $DB_FORCE_OVERWRITE"
if [ -z ${DB_FORCE_OVERWRITE+x} ]; then 
  DB_FORCE_OVERWRITE=0
fi

#source Calculating Daily Fraction Rasters
if [ $scenario == 'nldas2' ]; then
  if $DAILY_DEFAULT; then
    cmd="$MET_SCRIPT_PATH/sh/calc_fraction_ts_wDefault $HOURLYVARKEY $DAILYVARKEY $FRACTIONVARKEY $RASTER_SQL_FILE $db_host $db_name $END_DATETIME"
    echo "Calling Calc Fraction Raster With Design Storm"
    echo $cmd
    eval $cmd
    exit
  else
	cmd="$MET_SCRIPT_PATH/sh/calc_fraction_ts $HOURLYVARKEY $DAILYVARKEY $FRACTIONVARKEY $RASTER_SQL_FILE $db_host $db_name $END_DATETIME"
    echo "Calling Calc Fraction Raster"
    echo $cmd
    eval $cmd
    exit
  fi
else
  echo "Skipping Create Fraction Rasters"
  exit
fi
