#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
set clean=0
# we need more than the standard data here
source $META_MODEL_ROOT/plugins/$MODEL/model_config
echo "Script dir:  $SCRIPT_DIR "
set tempbase=`basename $tempdir`

echo "cd $MODEL_ROOT/$MODEL_BIN/$SCRIPT_DIR/" # e.g. run/standard, or run_bhat/OneCommandWSM_P6_STRLOAD_SCENCF
echo "csh bhatt_run_etm_and_land_and_dat_simultaneously_oneseg.csh $scenario $segment $AVG_YEAR1 $AVG_YEAR2 $tempbase"
cd $MODEL_ROOT/$MODEL_BIN/$SCRIPT_DIR # e.g. run/standard, or run_bhat/OneCommandWSM_P6_STRLOAD_SCENCF
csh bhatt_run_etm_and_land_and_dat_simultaneously_oneseg.csh $scenario $segment $AVG_YEAR1 $AVG_YEAR2 $tempbase
