#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

echo "Generating Coverage Meteorology Analytics"


scr_args="$META_MODEL_ROOT/scripts/met/precip_coverage_summary.R $scenario $coverage $COVERAGE_BUNDLE $COVERAGE_FTYPE $MET_MODEL_VERSION $COVERAGE_PRECIP_FILE" 
echo "Rscript $scr_args"
Rscript $scr_args 
