#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

if [[ "$GEO_MET_MODEL" != "lm_simple" ]]; then
  exit
fi

echo "Creating simple linear model (TBD)"

stats_file=`basename $MODEL_STATS`
json_file=`basename $MODEL_JSON`
echo "Rscript $META_MODEL_ROOT/scripts/precip/mon_lm_analysis.R $WEEKLY_PRECIP_FILE precip_cfs obs_flow mo $json_file $stats_file"
Rscript $META_MODEL_ROOT/scripts/precip/mon_lm_analysis.R $WEEKLY_PRECIP_FILE precip_cfs obs_flow mo $json_file $stats_file
install -D $json_file $MODEL_JSON 
install -D $stats_file $MODEL_STATS
