#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

if [[ "$GEO_MET_MODEL" != "lm_simple" ]]; then
  exit
fi

echo "Creating simple linear model (TBD)"

# even though we might have need fo the stats, but they are included in the json file
json_file=`basename $MODEL_JSON`
rate_file=`basename $RATING_FILE`
echo "Rscript $META_MODEL_ROOT/scripts/precip/mon_lm_analysis.R \"$WEEKLY_PRECIP_FILE\" precip_cfs obs_flow mo \"$json_file\" \"$rate_file\""
Rscript $META_MODEL_ROOT/scripts/precip/mon_lm_analysis.R "$WEEKLY_PRECIP_FILE" precip_cfs obs_flow mo "$json_file" "$rate_file"
install -D $json_file "$MODEL_JSON" 
install -D $rate_file "$RATING_FILE"
