#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

if [[ "$GEO_MET_MODEL" != "lm_simple" ]]; then
  exit
fi

echo $RATING_EXPANSION

if [[ "$RATING_EXPANSION" != "true" ]]; then
  exit
fi

echo "Expanding Simple LM timeseries"

json_file=`basename $MODEL_JSON`
rate_file=`basename $RATING_FILE`
echo "Rscript $META_MODEL_ROOT/scripts/met/predictedSimpleLM_cmd.R \"$WEEKLY_PRECIP_FILE\" \"$MODEL_JSON\" \"$rate_file\""
Rscript $META_MODEL_ROOT/scripts/met/predictedSimpleLM_cmd.R $WEEKLY_PRECIP_FILE $MODEL_JSON $rate_file
install -D $rate_file "$RATING_FILE"
