#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

if [[ "$GEO_MET_MODEL" != "storm_volume" ]]; then
  exit
fi

echo "Finding storm events"

scr="Rscript $META_MODEL_ROOT/scripts/met/QC_storms.R"
cmd="$scr $DAILY_PRECIP_FILE $STORM_EVENT_STATS_FILE $STORM_EVENT_FLOW_FILE"
echo "Running: $cmd"
$cmd