#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

if [[ "$GEO_MET_MODEL" != "storm_volume" ]]; then
  exit
fi

echo "Finding regressions from storm events and statistics"

#Where should output JSON be stored?
# even though we might have need fo the stats, but they are included in the json file
json_file=`basename $MODEL_JSON`
rate_file=`basename $RATING_FILE`

scr="Rscript $META_MODEL_ROOT/scripts/met/mon_lm_JSON.R"
cmd="$scr $STORM_EVENT_STATS_FILE $json_file $rate_file $STORMSEP_REGRESSION_METHOD"
echo "Running: $cmd"
$cmd
install -D $json_file "$MODEL_JSON" 
install -D $rate_file "$RATING_FILE"