#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

if [[ "$STORMSEP_PLOT" ]]; then
  exit
fi
if [[ "$GEO_MET_MODEL" != "storm_volume" ]]; then
  exit
fi


#Where are combined flow precip data file stored?
comp_dataFilePath=$DAILY_PRECIP_FILE
#Where to get data from process 02-stormAnalysis
stormStatsPath=$STORM_EVENT_FLOW_FILE
#Where to get data from process 03-stormStatistics
stormPath=$STORM_EVENT_STATS_FILE
# Directory to store plots in. 
pathToWrite=$STORM_EVENT_PRECIP_PLOT_DIR
# The USGS gage number or hydro ID of the coverage that will be used to store
# this data with unique names
plotDetails=$USGS_GAGE

echo "Plots to be written to: ${pathToWrite}"

if [ -d "$pathToWrite" ]; then
  mkdir $pathToWrite
else
  #While plotting, must clear existing plots. 
  rm -f "${pathToWrite}/stormPlot_${plotDetails}_*.png"
fi


cmd="Rscript $META_MODEL_ROOT/scripts/met/stormEventsLM_cmd.R $comp_dataFilePath $stormPath $stormStatsPath $pathToWrite $plotDetails $MET_DATA_SOURCE $MET_SCRIPT_PATH"
echo "Running: $cmd"
eval $cmd