#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

if [[ "$GEO_MET_MODEL" != "storm_volume" ]]; then
  exit
fi

echo "Using predicted flow to find ratings"

scr="Rscript $META_MODEL_ROOT/scripts/met/predict_flow.R"
cmd="$scr $STORM_EVENT_STATS_FILE $MODEL_JSON"
echo "Running: $cmd"
$cmd