#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

echo "Creating model rating timeseries."


rating_file=`basename $RATING_TS_FILE`

if [[ "$RATING_EXPANSION" != "true" ]]; then
  RATING_TS_SCALE=monthly
else
  RATING_TS_SCALE=weekly
fi

echo "Rscript $META_MODEL_ROOT/scripts/precip/create_rating_ts.R \"$DAILY_PRECIP_FILE\" \"$RATING_FILE\" \"$rating_file\" \"$RATING_TS_SCALE\""
Rscript $META_MODEL_ROOT/scripts/precip/create_rating_ts.R "$DAILY_PRECIP_FILE" "$RATING_FILE" "$rating_file" $RATING_TS_SCALE
install -D $rating_file $RATING_TS_FILE