#!/bin/bash
# loads the args, the raster specific config and change to temp dir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

#Need to confirm that model property is attached to feature
#Need to confirm that scenario property is attached to model property
#Need to send timeseries to db


outfile=`basename $modelPropfname`

echo "Checking ${db_name} to confirm that model property ${modelPropName} exists"
#Run a query to confirm existence of ${modelPropName}
modelProp_sql="
\\set modelPropVarkey '$modelPropVarkey' \n
\\set hydrocode  '$coverage' \n
\\set modelPropName '$modelPropName' \n
\\set fname '${modelPropfname}' \n

copy ( 
	SELECT count(*)
	FROM dh_properties as p
	LEFT JOIN dh_variabledefinition as v
	ON p.varid = v.hydroid
	WHERE v.varkey = :'modelPropVarkey'
		AND p.featureid = :'hydrocode'
		AND p.propname = :'modelPropName'
	
) to :'modelPropfname' WITH HEADER CSV;"

# turn off the expansion of the asterisk
set -f
echo -e $modelProp_sql > $modelProp_sql_file 
cat $modelProp_sql_file | psql -h $db_host $db_name
#Get file with count
sftp ${db_host}:"${modelPropfname}" "${tempdir}/${outfile}"

#If there are no rows, than this model property must be written into $db_name
content=`cat ${tempdir}/${outfile}`
if [ "$content" -eq 0 ];then 
	modelProp_sql="
	\\set modelPropVarkey '$modelPropVarkey' \n
	\\set hydrocode  '$coverage' \n
	\\set modelPropName '$modelPropName' \n
	
	insert into dh_properties(propvalue,featureid,varid,status,module,
							propname,startdate,enddate,bundle,entity_type)
	SELECT '',f.hydroid,v.hydroid,1,'',
		:'modelPropName','','','dh_properties','dh_feature'
	FROM dh_feature as f
	LEFT JOIN dh_variabledefinition as v
	ON (v.varkey = :'modelPropVarkey')
	WHERE f.hydrocode = :'coverage';"

	# turn off the expansion of the asterisk
	set -f
	echo -e $modelProp_sql > $modelProp_sql_file 
	cat $modelProp_sql_file | psql -h $db_host $db_name
fi