#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3

source $MODEL_ROOT/config/control/script/${scenario}.con
echo "Changing to $tempdir"
cd $tempdir

if ($RUN_ANNLOAD == 1) then
  #   echo 'RUN AVG LOAD :: Started  ' `date` >> $SCENARIO_LOG
  $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR/bhatt_run_annload_oneseg.csh $scenario $segment $tempdir $MODEL_ROOT
endif
