#!/bin/csh
# Run post-process extract routine
# note: this was moved from the hspf model tree, since the expected files were not correct.
#       in fact, this script was also incomplete, and did not set output_file_path, so it crashed the run
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
cd $tempdir

if (! $?MODEL_VERSION_CODE) then
  echo "Variable MODEL_VERSION_CODE is not defined. Cannot push results to REST" >> problem
  echo "Verify that MODEL_VERSION_CODE and LAND_FTYPE are set in config/control/script/${scenario}.con" >> problem
  exit
endif
set vers = $MODEL_VERSION_CODE
set ftype = $LAND_FTYPE
set image_file_path=$CBP_EXPORT_DIR/land/$scenario/images
echo "This contains model image file of base flow simulation" > /tmp/README.txt
install -D /tmp/README.txt "${image_file_path}/"
# load perlands and implnds variables
source $MODEL_ROOT/run_bhatt/fragments/set_landuse
foreach landuse ($perlnds $implnds)
  set output_file_path="$CBP_EXPORT_DIR/land/$scenario/pwater/${landuse}${seg}_pwater.csv"
  set pwater_file = "$image_file_path/${landuse}${segment}_pwater.csv"
  set img_file = "${image_file_path}/${landuse}${segment}_pwater.png"
  set img_url = "$CBP_EXPORT_URL/land/$scenario/images/${landuse}${segment}_pwater.png"
  echo "Running: Rscript $META_MODEL_ROOT/scripts/land/aglzuz_storage.R $segment $scenario $landuse $output_file_path $img_file $vers $ftype $img_url "
  Rscript $META_MODEL_ROOT/scripts/land/aglzuz_storage.R $segment $scenario $landuse $output_file_path $img_file $vers $ftype $img_url 

end
