#!/bin/csh
# THis exports hydro dat from the hdf5 to a CSV for import into the river wdm
# this is doen here because the sediment routine needs to have he hydro data 
# in the WDM to complete.  It is later used by the next downstream
# do NOT be tempted to move this to "link", as the sediment will fail!
set scenario=$1
set segment=$2
set seg = $segment
set tempdir=$3
set tree = $MODEL_ROOT
source $META_MODEL_ROOT/models/$MODEL/model_config
echo "Locating: cd $tempdir"
cd $tempdir
set MODEL_VERSION_CODE=`cbp get_config ${scenario} script MODEL_VERSION_CODE`
echo "SETTING MODEL STATUS"
echo "Notice: Rscript $META_MODEL_ROOT/scripts/rest/set_model_status.R $seg $scenario $MODEL_VERSION_CODE $RIVER_FTYPE 1 \"Model Run beginning.\""
Rscript $META_MODEL_ROOT/scripts/rest/set_model_status.R $seg $scenario $MODEL_VERSION_CODE $RIVER_FTYPE 1 "Model run beginning."

