#!/bin/csh
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3

# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
cd $tempdir

set inp = $seg'.uci'
if (!(-e $inp)) then
  echo 'HSPF UCI for segment ' $seg ' named'
  echo $inp 'does not exist'
  echo 'Did the prior step get_uci complete?'
  exit
endif

#echo $inp | $HSPF_EXEC 
cbp run_river.csh $scenario $segment
# @todo: put in run execution checks like normal HSPF has
