#!/bin/csh
# Run post-process extract routine
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
# copy the final wdm back to the common scenario storage space
cd $tempdir
cp $seg'.wdm' $MODEL_ROOT/tmp/wdm/river/$scenario/stream/ -f

