#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


if [ "$datasource" != "noaa_drought" ]; then
  exit
fi

# make sure we have our data dirs
if [ ! -d "$base_dir/$yr" ]; then
    echo "Doing: mkdir $base_dir/$yr"
    mkdir $base_dir/$yr
fi
if [ ! -d "$base_dir/$yr/$jday" ]; then
    echo "Doing: mkdir $base_dir/$yr/$jday"
    mkdir $base_dir/$yr/$jday
fi  

url="${BASE_URI}/$yr/$mo/$da/nws_precip_wytd_$yr$mo${da}_conus.tif"

#Only download if file does not yet exist OR if the download date does not match today's date.
pfile="${src_dir}/noaa_raster_$jday.tif"
pexist_date=""
todays_date=`date +"%Y-%m-%d"`
if [ -e "$pfile" ]; then
  # check the date
  pexist_date=`date -r $pfile +"%Y-%m-%d"`
fi
if [ "$pexist_date" == "$todays_date" ]; then
  echo "NOAA multiband raster for ${yr}-${mo}-${da} has already been downloaded today. Skipping."
  exit
fi
# remove all previous files
rm $src_dir/* -f 
# This multi-banded tif is used in other meta model workflow as well
wget $url -O "${src_dir}/noaa_raster_$jday.tif"