#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


if [ "$datasource" != "daymet" ]; then
  exit
fi

# Changing to 
echo "Changing to temp dir: cd $tempdir "
cd $tempdir
# load the functions used herein
source $MET_SCRIPT_PATH/daymet/downloadDailyDaymet.sh
echo "Verifying $base_dir/$yr and $base_dir/$yr/$jday" 
# make sure we have our data dirs
if [ ! -d "$base_dir/$yr" ]; then
    echo "Doing: mkdir $base_dir/$yr"
    mkdir $base_dir/$yr
fi
if [ ! -d "$base_dir/$yr/$jday" ]; then
    echo "Doing: mkdir $base_dir/$yr/$jday"
    mkdir $base_dir/$yr/$jday
fi  

echo "Getting data for month ${yr}-${mo}-${da}..."
#Download the daily PRISM data for target day, reporject, and crop
if [ "$jday" == "366" ]; then
  # daymet does not have Dec 31 on leap years, so we copy from PRISM
  echo "This is the last day of a leap year, daymet has no data."
  PRISM=`cbp get_config $scenario met PRISM_DIR`
  echo "Copying prism from $PRISM"
  cp $PRISM/$yr/$jday/* $base_dir/$yr/$jday/
else
  downloadDaymet $yr-$mo-$da $bboxnorth $bboxsouth $bboxwest $bboxeast
fi
if [ "$originalFile" == "-9999" ]; then
  echo "daymet download could not find $download_name ... exiting. " > problem
  exit
fi

# stash in the daymet dowload place.
cp ORIGINAL_*${yr}-${mo}-${da}* $base_dir/$yr/$jday/
