#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

if [ "$datasource" != "nldas2" ]; then
  exit
fi

echo "Downloading from "${datasource}

echo "Trying ${datasource} for ${ddate}"

echo "In: cd $base_dir"
cd $base_dir
echo "Clearing old: rm $yr/$jday/*"
rm $yr/$jday/*
echo "Running: ./get_nldas_data $yr $jday $yr"
./get_nldas_data $yr $jday $NLDAS_ROOT
