#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config


if [ "$datasource" != "PRISM_normal" ]; then
  exit
fi

# Changing to load the functions used herein
echo "Verifying $base_dir/$yr and $base_dir/$yr/$jday" 
# make sure we have our data dirs
if [ ! -d "$base_dir/$yr" ]; then
    echo "Doing: mkdir $base_dir/$yr"
    mkdir $base_dir/$yr
fi
if [ ! -d "$base_dir/$yr/$jday" ]; then
    echo "Doing: mkdir $base_dir/$yr/$jday"
    mkdir $base_dir/$yr/$jday
fi  

# Check the file date from a previous download, do NOT double up as we can be banned for such things!
pfile="$base_dir/$yr/$jday/prism_norm_downloaded"
pexist_date=""
todays_date=`date +"%Y-%m-%d"`
if [ -e "$pfile" ]; then
  # check the date
  pexist_date=`date -r $pfile +"%Y-%m-%d"`
fi
if [ "$pexist_date" == "$todays_date" ]; then
  echo "PRISM file for ${yr}-${mo}-${da} has already been downloaded today, and cannot be downloaded twice in a day. Skipping."
  exit
fi
# remove all previous prism files
rm "$base_dir/$yr/$jday/*" -f

echo "Getting data for month ${yr}-${mo}-${da}..."


echo "Getting data from PRISM REST service..."
echo "Trying: wget $BASE_URI/$YYYY$MM$DD "
#Download and unzip the raster from the PRISM webservices
wget "$BASE_URI/prism_ppt_us_25m_2020$MM$DD_avg_30y.zip"
unzip "prism_ppt_us_25m_2020$MM$DD_avg_30y.zip"

download_name="prism_ppt_us_25m_2020${MM}${DD}_avg_30y.${FILE_EXT}"

if [ ! -e "$download_name" ]; then
  echo "PRISM download could not find $download_name ... exiting. " > problem
  exit
fi

# set a file with the date that we downloaded for future reference.
touch $pfile
