#!/bin/bash
# loads the met specific config
met_config=`find_config met.config`
if [ "$met_config" = "" ]; then
  met_config="$META_MODEL_ROOT/models/raster_met/met/met.config"
fi
echo "Loading met_config from $met_config"
. $met_config

echo "Downloading from "${datasource}

echo "Trying ${datasource} for ${ddate}"

