#!/bin/bash

ddate=$1
datasource=$2
tempdir=$3

# loads the raster specific config
raster_config=`find_config raster.config`
if [ "$raster_config" = "" ]; then
  raster_config="$META_MODEL_ROOT/models/raster_met/raster.config"
fi
. $raster_config


if [ "$datasource" == "PRISM" ]; then
  rm *${yr}${mo}${da}*
fi
