#!/bin/bash
# loads the script args, raster specific config and change to tempdir
wdm_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  wdm_config="$META_MODEL_ROOT/models/raster_met/wdm/wdm.config"
fi
. $wdm_config


