#!/bin/bash
# loads the args, the raster specific config and change to tempdir
wdm_config=`find_config wdm.config`
if [ "$wdm_config" = "" ]; then
  wdm_config="$META_MODEL_ROOT/models/raster_met/wdm/wdm.config"
fi
. $wdm_config

# insure that the new-fangled lseg_csv directory is linked to the old structure just in case it is needed 
# (tho it should not be )
ln -s $COVERAGE_WDM_DIR $NLDAS_ROOT/out/lseg_csv/${scenario}
