#!/bin/bash
# loads the args, the raster specific config and change to tempdir
wdm_config=`find_config wdm.config`
if [ "$wdm_config" = "" ]; then
  wdm_config="$META_MODEL_ROOT/models/raster_met/wdm/wdm.config"
fi
. $wdm_config

# note: we use varkey here as the "pdname" attribute since this var seems somewhat superfluous
#       and the varkey will in fact associate with a specific time period dataset
echo "Copying processed met data $COVERAGE_WDM_DIR/lseg_csv/"
echo "into directory $oDir"
for i in `ls $COVERAGE_WDM_DIR/${coverage}.*`; do
  csv_file_name=`basename $i`
  echo "install -D $i $oDir/$csv_file_name"
  install -D $i $oDir/$csv_file_name
done
