#!/bin/bash
# loads the args, the raster specific config and change to tempdir
wdm_config=`find_config wdm.config`
if [ "$alt_config" = "" ]; then
  alt_config="$META_MODEL_ROOT/models/raster_met/alt/alt.config"
fi
. $alt_config

# First we determine where the source file is.
# In general, many of our BASELINE data sets may not have been made from 
# raasters and residing in $MET_EXPORT_DIR/$BASELINE_MET_SCENARIO/et/${coverage}-${MET_DATA_SOURCE}-all.csv
# But some may, so we check here. And then look for lseg_csv versions
if [ ! -e $BASELINE_ET_FILE ]; then
  echo "Cannot find $BASELINE_ET_FILE. Looking for $BASEMODEL_ET_FILE"
  if [ ! -e $BASEMODEL_ET_FILE ]; then
    echo "Error: Cannot find $BASEMODEL_ET_FILE . Exiting." 
    echo "Error: Cannot find $BASEMODEL_ET_FILE . Exiting." > $tmpdir/problem
    exit
  fi
  echo "Converting WDM headerless file to CSV."
  Rscript $META_MODEL_ROOT/scripts/wdm/wdm_export_csv.R 
fi

# once we have the ET file and TEMP file we can scale TEMP then calculate ET

# call Rscript to format data as WDM importable
RSC="$META_MODEL_ROOT/scripts/met/scale_et_cbp_hargreaves.R"
outfile=`basename $ET_MOD_FILE`

echo "Rscript $RSC $BASELINE_ET_FILE $ASELINE_TEMP_FILE $MOD_TEMP_FILE et_in temp $outfile et_in $outfile"
#Rscript $RSC $BASELINE_ET_FILE $ASELINE_TEMP_FILE $MOD_TEMP_FILE et_in temp $outfile et_in $outfile
#install -D $outfile $ET_MOD_FILE
