#!/bin/bash
# loads the args, raster & geo specific config AND CHANGE TO TEMPDIR
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config

echo "Calling: Rscript $META_MODEL_ROOT/scripts/qa/R/agws_04_exithandler.R \"$GAGEID\""
Rscript $META_MODEL_ROOT/scripts/qa/R/agws_04_exithandler.R "$GAGEID"
