#!/bin/bash
# loads the args, raster & geo specific config AND CHANGE TO TEMPDIR
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config
# BEGIN - actually loading local data

echo "Identifying and analyzing baseflow events for ${coverage}"
# Now, we should have a method to save a given coverages gage, but since 
# our basic use case is for gage catchments, we can count on the fact that the gage hydrocode
# contains the USGS gage ID
gageid=`echo $coverage | sed 's/[^[:digit:]]\+//g'`
outfile="bf_events_${coverage}.csv"
# TODO: put FLOWCOL in con file somewhere so we can run model info through this?
FLOWCOL='obs_flow' # for now we assume the standard obs_flow from the previous workflow step
DATECOL='obs_date'
echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/event_identification.R \"$COVERAGE_FLOW_FILE\" \"$DATECOL\" \"$FLOWCOL\" \"$coverage\" \"FALSE\" \"FALSE\" \"$outfile\""
Rscript $META_MODEL_ROOT/scripts/usgs/event_identification.R "$COVERAGE_FLOW_FILE" "$DATECOL" "$FLOWCOL" "$coverage" "FALSE" "FALSE" "$outfile"
# note: the install -D command create the destination directory path if it doesn't exist
echo "Running: install -D $outfile ${USGS_DATA_DIR}/agws/${outfile}"
install -D $outfile "${USGS_DATA_DIR}/agws/${outfile}"
