#!/bin/bash
# loads the args, raster & geo specific config AND CHANGE TO TEMPDIR
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config
# BEGIN - actually loading local data

echo "Identifying all potential baseflow events for ${coverage}"

# TODO: put FLOWCOL in con file somewhere so we can run model info through this?
FLOWCOL='Flow'
DATECOL='Date'

echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_events.R \"$EVENTS_FILE\" \"$DATECOL\" \"$FLOWCOL\" \"$coverage\" \"$BASEFLOW_EVENTS_FILE\" \"$SITENOCOL\" \"$BASEFLOW_MIN_EVENT_LENGTH\"" 
Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_events.R "$EVENTS_FILE" "$DATECOL" "$FLOWCOL" "$coverage" "$BASEFLOW_EVENTS_FILE" "$SITENOCOL" "$BASEFLOW_MIN_EVENT_LENGTH"
# note: the install -D command create the destination directory path if it doesn't exist
echo "Running: install -D $BASEFLOW_EVENTS_FILE ${USGS_DATA_DIR}/agws/${BASEFLOW_EVENTS_FILE}"
install -D $BASEFLOW_EVENTS_FILE "${USGS_DATA_DIR}/agws/${BASEFLOW_EVENTS_FILE}"
