#!/bin/bash
# loads the args, raster & geo specific config AND CHANGE TO TEMPDIR
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config
# BEGIN - actually loading local data

echo "Summarizing recession coefficients for each baseflow events for ${coverage}"
echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_regression_df.R \"$BASEFLOW_TRIM_STATS_FILE\" $GAGEID \"$BASEFLOW_SUMMARY_PREQC_DF\""
Rscript $META_MODEL_ROOT/scripts/usgs/baseflow_regression_df.R "$BASEFLOW_TRIM_STATS_FILE" "$GAGEID" "$BASEFLOW_SUMMARY_PREQC_DF"

if [ ! -e "$BASEFLOW_SUMMARY_PREQC_DF" ]; then
  echo "Baseflow summary failed; could not generated $BASEFLOW_SUMMARY_PREQC_DF ... exiting. " > problem
  exit 1
fi