#!/bin/bash
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config

echo "Looking for potential outliers in regression for ${coverage}"

echo "Calling: Rscript $META_MODEL_ROOT/scripts/usgs/regression_outliers.R \"$BASEFLOW_SUMMARY_PREQC_DF\" \"$BASEFLOW_SUMMARY_DF\""
Rscript $META_MODEL_ROOT/scripts/usgs/regression_outliers.R "$BASEFLOW_SUMMARY_PREQC_DF" "$BASEFLOW_SUMMARY_DF"

# note: the install -D command create the destination directory path if it doesn't exist
echo "Running: install -D $BASEFLOW_SUMMARY_OUTLIERS_DF ${USGS_DATA_DIR}/agws/${BASEFLOW_SUMMARY_OUTLIERS_DF}"
install -D $BASEFLOW_SUMMARY_OUTLIERS_DF "${USGS_DATA_DIR}/agws/${BASEFLOW_SUMMARY_OUTLIERS_DF}"
