#!/bin/bash
# loads the args, raster & geo specific config AND CHANGE TO TEMPDIR
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config
# BEGIN - actually loading local data

echo "PLACEHOLDER: Generating Q-AGWRC lookup table for ${coverage}"
