#!/bin/bash
agws_config=`find_config agws.config`
if [ "$agws_config" = "" ]; then
  agws_config="$META_MODEL_ROOT/models/drought/agws/agws.config"
fi
. $agws_config

echo "Finding number of non-NA flow for ${coverage}"

echo "Calling: Rscript $META_MODEL_ROOT/scripts/misc/filelength_qc.R \"$GAGEID\" \"$COVERAGE_FLOW_FILE\" \"$GAGE_QC_DF\""
Rscript $META_MODEL_ROOT/scripts/misc/filelength_qc.R $GAGEID $COVERAGE_FLOW_FILE $GAGE_QC_DF
