#!/bin/csh
# Run post-process extract routine
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
cd $tempdir

set wdm=${segment}.wdm
set wdm3=ps_sep_div_ams_${scenario}_${segment}.wdm
cp /usr/local/lib/hspf/message.wdm ./

# create the basic wdm export of flow, ie. DSN 111
# file name will be [segment]_0111.csv
#   ex: JL1_7080_7190_0111.csv
if ( $?START_YEAR ) then
  echo "echo $wdm,$START_YEAR,$END_YEAR,111 | wdm2text"
  echo "$wdm,$START_YEAR,$END_YEAR,111" | wdm2text
  echo "echo $wdm3,$START_YEAR,$END_YEAR,3000 | wdm2text"
  echo "$wdm3,$START_YEAR,$END_YEAR,3000" | wdm2text
  echo "echo $wdm3,$START_YEAR,$END_YEAR,3007 | wdm2text"
  echo "$wdm3,$START_YEAR,$END_YEAR,3007" | wdm2text
  echo "echo $wdm3,$START_YEAR,$END_YEAR,3008 | wdm2text"
  echo "$wdm3,$START_YEAR,$END_YEAR,3008" | wdm2text
endif
rm message.wdm
set csv_file="${segment}_0111.csv"
set hydr_file="${segment}_hydr.csv"
# TODO: convert this file into a _hydr compatible file
Rscript $META_MODEL_ROOT/scripts/h5/create_hspf_hydr.R $csv_file $hydr_file
echo "cp $hydr_file $CBP_EXPORT_DIR/river/$scenario/"
cp $hydr_file $CBP_EXPORT_DIR/river/$scenario/hydr/

# fixing times of csvs before join can happen
set divrcsv=ps_sep_div_ams_${scenario}_${segment}_3007'.csv'
echo "Time fix: ps_sep_div_ams_${scenario}_${segment}_3007'.csv'"
Rscript $META_MODEL_ROOT/scripts/misc/time_fix.R $divrcsv 'wdm' 'hour'

set divacsv=ps_sep_div_ams_${scenario}_${segment}_3008'.csv'
echo "Time fix: ps_sep_div_ams_${scenario}_${segment}_3008'.csv'"
Rscript $META_MODEL_ROOT/scripts/misc/time_fix.R $divacsv 'wdm' 'hour'

set pscsv=ps_sep_div_ams_${scenario}_${segment}_3000'.csv'
echo "Time fix: ps_sep_div_ams_${scenario}_${segment}_3000'.csv'"
Rscript $META_MODEL_ROOT/scripts/misc/time_fix.R $pscsv 'wdm' 'hour'

