#!/bin/csh
# Run post-process extract routine
# note: this was moved from the hspf model tree, since the expected files were not correct.
#       in fact, this script was also incomplete, and did not set output_file_path, so it crashed the run
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config
cd $tempdir

if (! $?MODEL_VERSION_CODE) then
  echo "Variable MODEL_VERSION_CODE is not defined. Cannot push results to REST" >> problem
  echo "Verify that MODEL_VERSION_CODE and LAND_FTYPE are set in config/control/script/${scenario}.con" >> problem
  exit
endif
set vers = $MODEL_VERSION_CODE
set ftype = $LAND_FTYPE
set image_file_path=$CBP_EXPORT_DIR/land/$scenario/images

set output_file_path="$CBP_EXPORT_DIR/land/$scenario/eos/${seg}_0111-0211-0411.csv"
echo "Running: Rscript $META_MODEL_ROOT/scripts/land/hsp_ro_stats.R $segment $scenario $output_file_path $image_file_path $vers $ftype"
Rscript $META_MODEL_ROOT/scripts/land/hsp_ro_stats.R $segment $scenario $output_file_path $image_file_path $vers $ftype

set RO_QA=`cbp get_config $scenario script RO_QA`
if ( $RO_QA != 1 ) then
  echo "Skipping detailed RO QA (to enable, set RO_QA = 1 in $MODEL_ROOT/config/control/script/${scenario}.con)"
  exit
endif

# tbd: load each lu and process, OR, just use the already aggregated RO file
# load perlands and implnds variables
#source $MODEL_ROOT/run_bhatt/fragments/set_landuse
#foreach landuse ($perlnds $implnds)
#  set output_file_path="$CBP_EXPORT_DIR/land/$scenario/pwater/${landuse}${seg}_pwater.csv"
#  Rscript $META_MODEL_ROOT/run/export/hsp_pwater.R $segment $scenario $landuse $output_file_path $image_file_path $vers $ftype
#  Rscript $META_MODEL_ROOT/run/export/hsp_pwater_stats.R $segment $scenario $landuse $output_file_path $image_file_path $vers $ftype
#end
