#!/bin/bash
# loads the args, raster & geo specific config and change to tempdir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config


# BEGIN - actually loading local data
echo "Aggregating precip for $coverage from "$datasource
outfile=`basename $COVERAGE_PRECIP_FILE`

echo "Calling: $MET_SCRIPT_PATH/sh/calc_raster_ts $coverage $varkey $RASTER_SQL_FILE ${RASTER_SUM_FILE} $db_host $db_name"
$MET_SCRIPT_PATH/sh/calc_raster_ts $coverage $varkey $RASTER_SQL_FILE $RASTER_SUM_FILE $db_host $db_name
sftp ${db_host}:"${RASTER_SUM_FILE}" "${tempdir}/${outfile}"
install -D "${tempdir}/${outfile}" $COVERAGE_PRECIP_FILE

