#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
set tree = $MODEL_ROOT
source $MODEL_ROOT/config/control/script/${scenario}.con
echo "Changing to  $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR"
cd $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR

######## Apply SPARROW Reservoir (Type II) Efficiency
echo $scenario $segment 1 | $tree/code/bin/reservoir_type_II.exe
