#!/bin/bash
# loads the args, the raster specific config and change to tempdir
alt_config=`find_config alt.config`
if [ "$alt_config" = "" ]; then
  alt_config="$META_MODEL_ROOT/models/raster_met/alt/alt.config"
fi
. $alt_config

if [ "$FACTOR_METHOD" != "LOOKUP" ]; then
  echo "FACTOR_METHOD = $FACTOR_METHOD, not a file lookup method. Skipping."
  exit
fi

# call a postgis routine to find the nearest neighbor
SSC="$META_MODEL_ROOT/scripts/misc/nearest_neighbor.sh"
# Copy the data from the nearest neighbor
outfile=`basename $TEMP_MOD_FILE`
echo "Running: $SSC $coverage $COVERAGE_BUNDLE $COVERAGE_FTYPE $COVERAGE_BUNDLE $neighbor_coverage_ftype $db_host $db_name"
nn=`$SSC $coverage $COVERAGE_BUNDLE $COVERAGE_FTYPE $COVERAGE_BUNDLE $neighbor_coverage_ftype $db_host $db_name`

echo "Running: Rscript $META_MODEL_ROOT/scripts/misc/copy_row.R $TEMP_FACTOR_FILE $coverage $nn FIPS_NHL"
Rscript $META_MODEL_ROOT/scripts/misc/copy_row.R $TEMP_FACTOR_FILE $coverage $nn FIPS_NHL

