#!/bin/csh
# Run post-process extract routine
set scenario=$1
set segment=$2
set seg=$segment # this is for backwards compatibility with scripts source
set tempdir=$3
# Load configuration
source $META_MODEL_ROOT/models/$MODEL/model_config

# insure that we have all the required directories
echo "Checking for paths to save in $CBP_EXPORT_DIR"
if ( ! ( -d $tempdir ) ) then
  echo "Creating $tempdir"
  mkdir $tempdir
endif
if ( ! ( -d $CBP_EXPORT_DIR/river ) ) then
  mkdir $CBP_EXPORT_DIR/river
endif
if ( ! ( -d $CBP_EXPORT_DIR/river/$scenario ) ) then
  mkdir $CBP_EXPORT_DIR/river/$scenario
endif
if ( ! ( -d $CBP_EXPORT_DIR/river/$scenario/hydr ) ) then
  mkdir $CBP_EXPORT_DIR/river/$scenario/hydr
endif
if ( ! ( -d $CBP_EXPORT_DIR/river/$scenario/json ) ) then
  mkdir $CBP_EXPORT_DIR/river/$scenario/json
endif
if ( ! ( -d $CBP_EXPORT_DIR/river/$scenario/hydr/images ) ) then
  mkdir $CBP_EXPORT_DIR/river/$scenario/hydr/images
endif
