# parse things like 
# input/param/for/P620171001WQf/PWATER.csv
# 
# TABLE->,PWAT-PARM1,PWAT-PARM1,PWAT-PARM1,PWAT-PARM1,PWAT-PARM1,PWAT-PARM1,PWAT-PARM1,PWAT-PARM1,PWAT-PARM1,PWAT-PARM2,PWAT-PARM2,PWAT-PARM2,PWAT-PARM2,PWAT-PARM2,PWAT-PARM2,PWAT-PARM2,PWAT-PARM3,PWAT-PARM3,PWAT-PARM3,PWAT-PARM3,PWAT-PARM3,PWAT-PARM3,PWAT-PARM3,PWAT-PARM4,PWAT-PARM4,PWAT-PARM4,PWAT-PARM4,PWAT-PARM4,PWAT-PARM4,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-INTERCEP,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-UZSN,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-MANNING,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,MON-LZETPARM,PWAT-STATE1,PWAT-STATE1,PWAT-STATE1,PWAT-STATE1,PWAT-STATE1,PWAT-STATE1,PWAT-STATE1
# VARS->,CSNO,RTOP,UZFG,VCS,VUZ,VMN,VIFW,VIRC,VLE,FOREST,LZSN,INFILT,LSUR,SLSUR,KVARY,AGWR,PETMAX,PETMIN,INFEXP,INFILD,DEEPFR,BASETPR,AGWETP,CEPSC,UZSN,NSUR,INTFW,IRC,LZETP,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,CEPS,SURS,UZS,IFWS,LZS,AGWS,GWVS
param_file = "input/param/for/P620171001WQf/PWATER.csv"
landseg = "N51135"
table_name = "PWAT-PARM2"
param_name = "LZSN"

param_file_raw <- read.csv(param_file, header=FALSE)
param_tables <- param_file_raw[1,]
param_vars <- param_file_raw[2,]

# find the table match for the desired land seg
# (param_file_raw[param_file_raw$V1 == "N51135",])[,names(param_vars[,param_tables == "PWAT-PARM2"])]
# (index)    V11      V12      V13      V14      V15       V16      V17
# 171       0.31 12.13198 0.021138 459.0762 0.092563 0.100E-05 0.920000

target_table <- (param_file_raw[param_file_raw$V1 == landseg,])[,names(param_vars[,param_tables == table_name])]

if (param_name == "") {
  return_vals <- target_table
} else {
  return_vals <- target_table[,names(param_vars[which(param_vars == param_name)])]
}

print(as.numeric(return_vals))
