#!/bin/bash
# given pid
# Returns pid elid object_class custom1 custom2
. om_config
sql="
\\o \n


  select m.pid, e.propvalue as elid, o.propcode as object_class, 
    c1.propcode as custom1, c2.propcode as custom2
  from dh_properties as m
  left outer join dh_properties as e
  on (
    m.pid = e.featureid
    and e.propname = 'om_element_connection'
  )
  left outer join dh_properties as o
  on (
    m.pid = o.featureid
    and o.propname = 'object_class'
  )
  left outer join dh_properties as c1
  on (
    m.pid = c1.featureid
    and c1.propname = 'custom1'
  )
  left outer join dh_properties as c2
  on (
    m.pid = c2.featureid
    and c2.propname = 'custom2'
  )
  WHERE m.pid = $1
"

#echo $sql

set -f
# can't echo this to stdout or it clobbers script pipes
if [ "$3" == "1" ]; then
  echo -e "$sql | psql --csv -A --field-separator=',' -t -h $DB_HOST $DB_NAME"
fi
echo -e $sql | psql --csv -A --field-separator="," -t -h $DB_HOST $DB_NAME
