#!/bin/bash
# loads the args, the raster specific config and change to tempdir
om_config=`find_config om.config`
if [ "$om_config" = "" ]; then
  om_config="$META_MODEL_ROOT/models/om/om.config"
fi
. $om_config

if [ "$RUN_METHOD" != "run_model" ]; then
  exit
fi


# Example command:
cd /var/www/html/om/ 
# NOT YET WORKING - THE ARGUMENTS BELOW ARE ALL FOR SHAKE TREE
scr="/usr/bin/php -f /var/www/html/om/run_model.php"
args="$SHAKE_TREE_MODE $elid $scenario $START_DATE $END_DATE $CACHE_DATE $RERUN_MODE $DOMAIN_ID $QA_MODE $RUN_MODE $RUN_METHOD flow_mode=$FLOW_MODE $DEBUG_MODE $DT"

echo "Running: $scr $args"
#$scr $args
