#!/bin/bash
# loads the args, the raster specific config and change to tempdir
om_config=`find_config om.config`
if [ "$om_config" = "" ]; then
  om_config="$META_MODEL_ROOT/models/om/om.config"
fi
. $om_config

if [ "$RUN_METHOD" != "run_model" ]; then
  exit
fi

cache_valid=`$META_MODEL_ROOT/scripts/misc/check_cache $output_file '$CACHE_DATE'
if [ $cache_valid -eq 1 ];
  echo "Valid cache found for file $runfile ... using cached."
fi

# Example command:
cd /var/www/html/om/ 
# For now we disable the old, no longer used, VWP cache mode which allowed a mixed run with only a single active permit
CACHE_LIST=-1
CACHE_LEVEL=-1
CACHE_RUNID=-1

scr="/usr/bin/php -f /var/www/html/om/run_model.php"
args="$elid $runid $RUN_TYPE $START_DATE $END_DATE $CACHE_RUNID $CACHE_LIST $CACHE_LEVEL 0 $scenario"

echo "Running: $scr $args"
#$scr $args
