#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
if ( ! -d $tempdir ) then
  mkdir $tempdir
endif

# load model entity to get run_mode and flow_mode, timestep, start and end dates
# probably can do this with get_prop function?
# /usr/bin/php -f /var/www/html/om/run_shakeTree.php 1 elid runid sdate edate cdate xtype scen -1 6 normal varX=n 0 dt
# xtype = shake tree or standard
# - get elementid from segment and model_version (get version from config in scenario)
# Example command:
cd /var/www/html/om/ 
/usr/bin/php -f /var/www/html/om/run_shakeTree.php 1 $elid $scenario $start_date $end_date $cache_date 2 37 -1 6 normal flow_mode=$flow_mode 0 $dt
