#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3
# backward compat
set seg=$segment
set tree=$MODEL_ROOT
source $META_MODEL_ROOT/models/$MODEL/model_config
echo "Changing to $tempdir"
cd $tempdir

if (-e problem) then
  rm problem
endif

foreach lu ($perlnds $implnds)
  echo converting UCI for $lu segment $segment land scenario $scenario
  set uci_name="$MODEL_ROOT/tmp/uci/land/$lu/$scenario/${lu}${segment}.uci"
  hsp_uci_version $uci_name hsp2
end

