#!/bin/bash

. $META_MODEL_ROOT/models/om/om.config
runid=$scenario
object_class=`Rscript $META_MODEL_ROOT/scripts/rest/get_property.R dh_properties $pid object_class propcode`

echo "Sumarizing container: $META_MODEL_ROOT/scripts/om/summarize_element $elid $runid $model_version"
$META_MODEL_ROOT/scripts/om/summarize_element $elid $runid $model_version

