#!/bin/csh
set scenario=$1
set segment=$2
set tempdir=$3

source $MODEL_ROOT/config/control/script/${scenario}.con
echo "Changing to $tempdir"
#cd $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR
cd $tempdir
set land_scenario=$scenario
echo "Running: set land_scenario=`cbp get_config $scenario river 'LAND SCENARIO'`"
set land_config=`cbp get_config $scenario river "LAND SCENARIO"`

# todo: make this a function to be re-used
foreach scen_pair ( "$land_config" ) 
  set split = ($scen_pair)
  set domain = $split[1]
  set scen = $split[2]
  if ( ( "$domain" == 'all') || ("$domain" == "$segment") ) then
#  if ( ( "$domain" == "all") ) then
    set land_scenario = $split[2]
  endif
end 
echo "Found land_scenario = $land_scenario "
if ($RUN_ANNLOAD == 1) then
  #   echo 'RUN AVG LOAD :: Started  ' `date` >> $SCENARIO_LOG
  echo "Running: $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR/bhatt_run_annload_oneseg.csh $land_scenario $segment $tempdir $MODEL_ROOT"
  $MODEL_ROOT/$MY_HOME/$SCRIPT_DIR/bhatt_run_annload_oneseg.csh $land_scenario $segment $tempdir $MODEL_ROOT
endif
