#!/bin/csh
echo "Loading model configuration"
if (! $?MODEL_ROOT) then
  echo "Variable MODEL_ROOT is undefined.  Exiting."
  exit
endif
# what is the date?
# what is the julian day?
# what is the base file name?
# do we have a feature hydrocode?
# which database host?
echo "model_config finished."
# Define modules to loop through
set all_modules = ( met )
set all_run_steps = ( download process import analyze )
# these must exist, but are unused currently
set START_YEAR=""
set END_YEAR=""
set MODEL_BIN=""
