#!/bin/bash
# loads the args, the raster specific config and change to tempdir
geo_config=`find_config geo.config`
if [ "$geo_config" = "" ]; then
  geo_config="$META_MODEL_ROOT/models/raster_met/geo/geo.config"
fi
. $geo_config

echo "Joining flow and precip files for $coverage (To Be completed)"

echo "Calling: Rscript $META_MODEL_ROOT/scripts/precip/comp_data.R $COVERAGE_FLOW_FILE $DAILY_PRECIP_FILE $DAILY_PRECIP_FILE"
Rscript $META_MODEL_ROOT/scripts/precip/comp_data.R $COVERAGE_FLOW_FILE $DAILY_PRECIP_FILE $DAILY_PRECIP_FILE
