#!/bin/bash

scenario=$1
segment=$2
tempdir=$3

IFS='_' read sta_id riverseg <<< "$segment"
echo "Making model $segment for gage $sta_id and segment $riverseg"
ftype=`cbp get_config $scenario script RIVER_FTYPE`
hydrocode_prefix=`cbp get_config $scenario script RIVER_PREFIX`
hydrocode="${hydrocode_prefix}${riverseg}"
USGS_MODEL_CODE=`cbp get_config $scenario script USGS_MODEL_CODE`
MODEL_VERSION_CODE=`cbp get_config $scenario script MODEL_VERSION_CODE`
scr="${META_MODEL_ROOT}/scripts/usgs/make_usgs_gage_model.R"
echo "Running: Rscript $scr $segment $riverseg $hydrocode $ftype $sta_id $USGS_MODEL_CODE $MODEL_VERSION_CODE"
Rscript $scr $segment $riverseg $hydrocode $ftype $sta_id $USGS_MODEL_CODE $MODEL_VERSION_CODE
